### ISSUE TITLE
Ticking Entity Crashes relaing to Evokers Armorful 1.20.1

### ISSUE THREAD

**Issue by Anth1121** [mineblock11/Illagers-Wear-Armor-For-Fabric#23]
Version 3.1.3+1.20.1

Crash prevented with Neruina after multiple crashes i couldn't trace.

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2960.equals(Object)" because "id" is null
	at net.minecraft.class_8489.handler$zla000$apoli$setTableId(class_8489.java:525)
	at net.minecraft.class_8489.getLootTable(class_8489.java)
	at dev.imb11.armorful.util.ArmorfulUtil.getNaturalSpawnItemsFromLootTable(ArmorfulUtil.java:59)
	at dev.imb11.armorful.util.ArmorfulUtil.giveArmorNaturally(ArmorfulUtil.java:85)
	at net.minecraft.class_1634.handler$bai001$armorful$initializeArmor(class_1634.java:531)
	at net.minecraft.class_1634.method_5943(class_1634.java)
	at net.minecraft.class_1564$class_1567.method_7148(class_1564.java:278)
	at net.minecraft.class_1617$class_1620.method_6268(class_1617.java:188)
	at net.minecraft.class_4135.method_6268(class_4135.java:65)
	at net.minecraft.class_1355.method_38849(class_1355.java:120)
	at net.minecraft.class_1355.method_6275(class_1355.java:111)
	at net.minecraft.class_1308.method_6023(class_1308.java:771)
	at net.minecraft.class_1309.method_6007(class_1309.java:2673)
	at net.minecraft.class_1308.method_6007(class_1308.java:550)
	at net.minecraft.class_1588.method_6007(class_1588.java:44)
	at net.minecraft.class_3763.method_6007(class_3763.java:114)
	at net.minecraft.class_1309.method_5773(class_1309.java:2419)
	at net.minecraft.class_1308.method_5773(class_1308.java:351)
	at net.minecraft.class_1617.method_5773(class_1617.java:92)
	at net.minecraft.class_3218.method_18762(class_3218.java:739)
	at net.minecraft.class_1937.mixinextras$bridge$accept$204(class_1937.java)
	at com.bawnorton.neruina.handler.TickHandler.safelyTickEntities(TickHandler.java:117)
	at net.minecraft.class_1937.wrapOperation$fkp000$neruina$catchTickingEntities$notTheCauseOfTickLag(class_1937.java:13548)
	at net.minecraft.class_1937.method_18472(class_1937.java:480)
	at net.minecraft.class_3218.method_31420(class_3218.java:385)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:353)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by IMB11** [comment]
I am going to be migrating away from the datapack system very soon which should solve this problem.

**Comment by muhammedesadcomert** [comment]
I think this is also related to the issue: https://mclo.gs/nvaivNK
